### ISSUE TITLE
Using DNS over TLS (DoT)

### ISSUE THREAD

**Issue by James972138** [milgradesec/firefox-settings#4]
**Welcome
How do I enable Using DNS over TLS (DoT) in Firefox
search in
about:config
I didn't find it
Please help me**
![Screenshot 2022-11-30 at 02-05-50 1 1 1 1 — the Internet’s Fastest Privacy-First DNS Resolver](https://user-images.githubusercontent.com/119469652/204697288-b5aec943-c1cc-4ca5-ba9e-a9a0d26ec270.png)

**Comment by milgradesec** [comment]
Firefox only supports DNS over HTTPS, see [https://support.mozilla.org/en-US/kb/dns-over-https-doh-faqs#w_why-is-firefox-implementing-doh-and-not-dot](url)
You have DoH set up and working with Cloudflare servers, no change is needed.
