### ISSUE TITLE
Enabling ECH GREASE (or `security.tls.ech.grease_http3`)

### ISSUE THREAD

**Issue by airglow923** [milgradesec/firefox-settings#5]
Firefox supports [ECH GREASE](https://www.ietf.org/archive/id/draft-ietf-tls-esni-16.html#name-grease-ech) with the preference named `security.tls.ech.grease_http3`. I believe we can add this for additional security.

**Comment by milgradesec** [comment]
Thank you, I'll take a look at this preference

**Comment by milgradesec** [comment]
Just added this setting, Thank you!
